version: "3"

services:
  web:
    build:
      context: .
    entrypoint:
      - flask
      - run
      - --host=${HOST}
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    volumes:
      - .:/app
      - data:/database

volumes:
  data: