"""empty message

Revision ID: c7bb8c5cef01
Revises: ea7a5bfcec98
Create Date: 2022-09-06 16:31:39.891120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bb8c5cef01'
down_revision = 'ea7a5bfcec98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_import')
    op.drop_table('star')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('model', sa.VARCHAR(length=120), nullable=False),
    sa.Column('teff', sa.INTEGER(), nullable=False),
    sa.Column('logg', sa.INTEGER(), nullable=False),
    sa.Column('mass', sa.INTEGER(), nullable=False),
    sa.Column('stell_rad', sa.INTEGER(), nullable=False),
    sa.Column('dist', sa.INTEGER(), nullable=False),
    sa.Column('fuv', sa.INTEGER(), nullable=False),
    sa.Column('fuv_flag', sa.VARCHAR(length=120), nullable=True),
    sa.Column('nuv', sa.INTEGER(), nullable=False),
    sa.Column('nuv_flag', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_import',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=120), nullable=False),
    sa.Column('teff', sa.INTEGER(), nullable=False),
    sa.Column('logg', sa.INTEGER(), nullable=False),
    sa.Column('trgrad', sa.INTEGER(), nullable=False),
    sa.Column('cmtop', sa.INTEGER(), nullable=False),
    sa.Column('cmin', sa.INTEGER(), nullable=False),
    sa.Column('euv', sa.INTEGER(), nullable=False),
    sa.Column('fuv', sa.INTEGER(), nullable=False),
    sa.Column('nuv', sa.INTEGER(), nullable=False),
    sa.Column('j', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
